export const TRUCK_CHECK_LIST = [
  "CHECK LICENSE, REGISTRATION, EXTERIORSTICKERS",
  "FIRE EXTINGUISHER/REFLECTORS SECURED CERT",
  "HORN-DEFROSTERS GAUGES/SPEEDOMETER/SEATBELT",
  "MIRRORS AND SUPPORTS SECURITY CRACKS OPERATE",
  "WINDSHIELD WIPERS/WINDOW CRACKS, CONDITION",
  "CHECK ALL LIGHTS, TURN SIGNALS, MUD FLAPS",
  "CHECK ELECTRICAL WIRING, CONDITIONPROTECTION",
  "CHECK BATTERIES, TERMINALS, CABLE CONDITION",
  "WARNING DEVICES, AIR, OIL, TEMP, VACCUUM ,DTC’S",
  "RADIATOR AND HOSES, CONDITION, AND LEAKS",
  "BELTS-COMPRESSOR, FAN AND WATER PUMP",
  "HOOD, VISOR, GRILL, ENTRY STEP FOR MOUNTING",
  "AIRLINES-LEAKS CONDITION AND PROTECTION",
  "FUEL TANKS-LINES-PUMP, CONDITION AND PROTECTION",
  "MANIFOLD AND FLANGE GASKET, MUFFLER, CONDITION",
  "ENGINE MOUNTS, OIL AND FUEL LEAKS",
  "CLUTCH ADJUSTMENT AND FREEPLAY",
  "THROTTLE AND LINKAGE, AIR FILTER",
  "GENERATOR/ALTERNATOR, STARTER, WIRING",
  "TRACTOR PROTECTION VALVE, BREAK-AWAY TEST",
  "BRAKES-LINING, DRUMS, AND ADJUSTMENTS",
  "HOSES AND TUBING ,CONDITION",
  "AIR LEAKS AND 1 MIN BRAKE APPLICATION TEST",
  "AIR GOVERNER ADJUSTMENT, MIN 85 MAX 130",
  "IDENTIFY #1 AIR TANK-DRAIN-TEST CHECK VALVE",
  "ALL TANKS SECURE, DRAINS OPERABLE, DRAINED",
  "TIRES, WHEELS, NUTS AND STUDS CONDITION, PRESS",
  "PARKING BRAKE CONDITION, ADJUSTMENT",
  "EMERGENCY STOPPING SYSTEM, LABLED, OPERABLE",
  "RELEASE AFTER LOSS OF SERVICE AIR",
  "CHECK STEERING GEAR BOX MOUNTING FREE-LASH",
  "STEERING ARMS, DRAG LINKS AND TIE ROD ENDS",
  "FIFTH WHEEL CONDITION AND MOUNTING",
  "SPRINGS SHACKLES AND U-JOINTS-TORQUE ARMS",
  "CHECK FRAME, CROSS MEMBERS CONDITION CRACKS",
  "CHECK DRIVE SHAFT AND UNIVERSAL JOINTS",
  "TRANSMISSION, DIFFERENTIALS-MOUNTING, SEALS",
  "WHEEL SEALS LEAKS, HYDRAULIC BRAKES LEAK",
  "CLEAN UNDER CARRIAGE",
  "HAS THE BIT STICKER BEEN ATTACHED"
];



export const TRAILER_CHECK_LIST = [
  "LIGHTS-STOP ,TAIL, TURN-REFLECTORS",
  "AIR LEAKS-BRAKE SYSTEM",
  "AIR/HYDRAULIC LEAKS DUMP SYSTEM",
  "CRACKS IN BODY AND FRAME",
  "BRAKES-ADJUSTMENT DRUMS, NEAR CAM OVER",
  "SPRINGS, U-BOLTS TORQUE ARMS",
  "DRAWBAR-HITCH & SAFETY CABLE, CHECK STRANDS",
  "FIFTH WHEEL ON PULL TRAILER",
  "TIRES, WHEELS, NUTS AND STUDS",
  "FIFTH WHEEL ON PIN, WEAR AND SAFETY LOCK",
  "EMERGENCY RELAY VALVES, TANKS-MOUNTING",
  "TARPS",
  "BED FLOOR/BOX WALLS ,BODY FOR DAMAGE",
  "ELECTRICAL CONNECTORS",
  "AIRLINES-BETWEEN TRAILERS-GLADHANDS, RUBBERS",
  "MUDFLAPS AND FENDERS",
  "HAS THE BIT STICKER BEEN ATTACHED",
  "CHECK LICENSE, REGISTRATION, EXTERIOR STICKERS"
];















